[package]
name = "librust"
version = "0.1.0"
authors = ["chris <rc.local@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "librust"
crate-type = ["staticlib"] # Creates static lib

[dependencies]
